name: crypto_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.5.1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  riverpod_annotation: ^2.3.5
  dio: ^5.4.3+1
  flutter_hooks: ^0.20.5
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.1.0
  gap: ^3.0.1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  collection: ^1.18.0
  pretty_dio_logger: ^1.3.1
  fl_chart: ^0.67.0
  flutter_widget_from_html: ^0.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: any
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
